name: POS Integration EPIC
description: Master Issue for a POS Integration.
title: "[POS Integration]: "
labels: ["EPIC", "pos_integration"]
projects: ["ReceiptHero/3"]
body:
  - type: input
    id: sales_person
    attributes:
      label: Sales Responsible
      placeholder: Kuitti Keijo
    validations:
      required: true
  - type: input
    id: partner_contact
    attributes:
      label: Partner Contact
      placeholder: partner.contact@domain.com
    validations:
      required: true
  - type: input
    id: tech_meeting
    attributes:
      label: Technical meeting held
      placeholder: "2024-00-00"
    validations:
      required: true
  - type: input
    id: credetials_provided
    attributes:
      label: Sandbox credentials provided
      placeholder: "2024-00-00"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Features
      options:
        - label: Card Linking
          required: false
        - label: QR Code
          required: false
        - label: Email Receipts
          required: false
        - label: Receipt Archive
          required: false
        - label: Fiscalization
          required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: This integration is very special because...
    validations:
      required: true
  - type: input
    id: namespace
    attributes:
      label: Namespace
    validations:
      required: true
  - type: textarea
    id: test_users
    attributes:
      label: Test Users
      value: |
        - **Email**: USER_EMAIL
        - **Receipts in DynamoDB**: [USER#USER_ID](https://eu-central-1.console.aws.amazon.com/dynamodbv2/home?region=eu-central-1#item-explorer?index=GSI1&operation=QUERY&pk=USER%23USER_ID&sk=RECEIPT&skComparator=BEGINS_WITH&sorting=DESC&table=dev-Hero)
        - **Hubspot Company**: [COMPANY_NAME](https://app.hubspot.com/contacts/7265974/record/0-2/HS_ID)
